START_CASH = 100_000.0

RUN_WINDOW = "V7_RECHECK_DEV"

WINDOWS = {
    "V7_RECHECK_DEV": ((2023, 1, 3), (2023, 1, 31)),
    "V7_RECHECK_CHECK": ((2025, 6, 2), (2025, 6, 30)),
    "V7_ROBUSTNESS": ((2026, 7, 1), (2026, 7, 31)),
    "FAST_DEV": ((2023, 1, 3), (2023, 1, 31)),
    "FAST_CHECK": ((2025, 6, 2), (2025, 6, 30)),
    "PLUMBING_CHECK": ((2023, 3, 13), (2023, 3, 24)),
    "POSTFIX_WF": ((2024, 5, 1), (2025, 5, 30)),
    "WF_A": ((2023, 1, 3), (2023, 4, 28)),
    "WF_B": ((2023, 5, 1), (2023, 8, 31)),
    "WF_C": ((2023, 9, 1), (2023, 12, 29)),
    "WF_D": ((2024, 1, 2), (2024, 4, 30)),
    "HIST_HOLDOUT": ((2025, 6, 2), (2025, 12, 31)),
    "PROSPECTIVE_OOS": ((2026, 9, 25), (2026, 12, 31)),
}
BACKTEST_START, BACKTEST_END = WINDOWS[RUN_WINDOW]
TRADE_START = BACKTEST_START

TICKERS = [
    'AAPL','AMD','AMZN','SPY','QQQ','IWM','UVIX','SOXX','NVDA','INTC','META','NFLX','V','RGTI','TSLA','MU',
    'AMAT','MRVL','DELL','PLTR','GLD','GDX','SLV','SIL','COPX','FCX','SCCO','DBB','XLE','XOM','CVX','COP',
    'XLP','WMT','COST','KO','PEP','CAR','HTZ'
]
ANCHOR = 'SPY'
PRICE_LOOKBACK_BARS = 420
PRICE_LOOKBACK_DAYS = 420
MIN_HISTORY_ROWS = 80
TRADING_DAYS = 252.0
FORWARD_HORIZON_DAYS = 20
EWMA_LAMBDA = 0.94
OU_VARIANCE_HALFLIFE = 20.0
FORWARD_OU_WEIGHT = 0.60
FORWARD_EWMA_WEIGHT = 0.40
JUMP_Z = 2.50
JUMP_LOOKBACK = 120
TARGET_DTE = 20
OPTION_MIN_DTE = 10
OPTION_MAX_DTE = 35
OPTION_STRIKE_RANGE = 15
MAX_OPTION_CONTRACTS_PER_TICKER = None
PRIMARY_MAX_RELATIVE_BID_ASK_SPREAD = 0.50
LIQUIDITY_ABSOLUTE_SPREAD_OVERRIDE = 0.03
MAX_DEBIT_MULTIPLE_OF_MID = 1.25
ENABLE_LIQUID_FALLBACK = True
FALLBACK_TICKERS = ('SPY', 'NDX')
FALLBACK_DTES = (7, 1)
FALLBACK_MIN_DTE = 1
FALLBACK_MAX_DTE = 7
FALLBACK_MAX_RELATIVE_BID_ASK_SPREAD = 0.30
FALLBACK_EXIT_DTE = 0
NDX_OPTION_TARGET = 'NDXP'
DEFAULT_SABR_BETA = 0.60
SABR_MIN_POINTS = 7
SABR_MIN_IV = 0.03
SABR_MAX_IV = 3.50
SABR_MAX_ACCEPTED_RMSE = 0.10
SABR_MAX_NFEV = 150
MIN_SURFACE_RESIDUAL = 0.012
MIN_SURFACE_Z = 1.00
MIN_SHORT_IV_RV = 1.02
MAX_LONG_IV_RV = 0.98
ENABLE_SHORT_RICH = True
ENABLE_LONG_CHEAP = True
HMM_MIN_OBSERVATIONS = 80
HMM_N_STATES = 3
HMM_RANDOM_STATE = 42
N_PATHS = 5_000
MC_MAX_DAYS = 60
RISK_FREE_RATE = 0.04
VOL_MULTIPLIERS = (0.80, 1.00, 1.20)
PROFIT_TARGET_FRACTION = 0.50
STOP_LOSS_MULTIPLE = 2.00
MIN_EXIT_DTE = 7
CONTRACT_MULTIPLIER = 100.0
MIN_DOLLAR_COST_PER_LEG = 0.50
BASE_COMPLEX_ORDER_CAPTURE = 0.35
SIZE_IMACT_PER_EXTRA_CONTRACT = 0.05
ACTION_GRID = (0.00, 0.25, 0.50, 1.00)
POSITION_PCT_PER_ACTION = 10.0
MAX_TOTAL_DEFINED_RISK_PCT = 25.0
MAX_SINGLE_TRADE_RISK_PCT = 10.0
MAX_TICKER_RISK_PCT = 10.0
HJB_RANDOM_SEED = 42
HJB_RANDOM_STARTS = 24
HJB_MAX_PASSES = 25
EXECUTE_ORDERS = True
ENTRY_ORDER_TIMEOUT_MINUTES = 10
ENTRY_EXECUTION_MODE = 'NATURAL_MARKETABLE'
ENTRY_MARKETABLE_CUSHION = 0.01
MIN_CREDIT_FRACTION_OF_MID = 0.65
MIN_NET_CREDIT = 0.03
ENABLE_STRANGLE_FALLBACK = False
ENABLE_ASYMMETRIC_CARRY = True
STRANGLE_MIN_IV_RV = 1.00
STRANGLE_TARGET_DELTA = 0.16
STRANGLE_MIN_ABS_DELTA = 0.08
STRANGLE_MAX_ABS_DELTA = 0.25
STRANGLE_MAX_CANDIDATES = 12
STRANGLE_USE_CONTINUOUS_RV = True
UNCAPPED_MARGIN_NOTIONAL_PCT = 0.12
UNCAPPED_MAX_SINGLE_TRADE_RISK_PCT = 7.5
UNCAPPED_MAX_TICKER_RISK_PCT = 7.5
UNCAPPED_POSITION_PCT_PER_ACTION = 7.5
UNCAPPED_MAX_CONTRACTS_PER_TRADE = 1
ASYM_PUT_POSITION_PCT_PER_ACTION = 7.5
ASYM_PUT_MAX_SINGLE_TRADE_RISK_PCT = 7.5
ASYM_PUT_MAX_TICKER_RISK_PCT = 7.5
ASYM_PUT_MAX_CONTRACTS_PER_TRADE = 2
ASYM_CALL_POSITION_PCT_PER_ACTION = 3.75
ASYM_CALL_MAX_SINGLE_TRADE_RISK_PCT = 3.75
ASYM_CALL_MAX_TICKER_RISK_PCT = 3.75
ASYM_CALL_MAX_CONTRACTS_PER_TRADE = 1
ASYM_STRANGLE_POSITION_PCT_PER_ACTION = ASYM_CALL_POSITION_PCT_PER_ACTION
ASYM_STRANGLE_MAX_SINGLE_TRADE_RISK_PCT = ASYM_CALL_MAX_SINGLE_TRADE_RISK_PCT
ASYM_STRANGLE_MAX_TICKER_RISK_PCT = ASYM_CALL_MAX_TICKER_RISK_PCT
ASYM_STRANGLE_MAX_CONTRACTS_PER_TRADE = 1
ASYM_PACKAGE_ONLY_MANAGEMENT = True
ASYM_ALLOW_STANDALONE_CALL = False
ENABLE_LEGACY_FLY_EXECUTION = False
MANAGEMENT_FREQUENCY = 'DAILY_CLOSE'
MANAGE_INTERVAL_MINUTES = 5
LEG_STOP_LOSS_PCT = 0.15
STRATEGY_STOP_TRIGGER_PCT = 0.08
STRATEGY_HARD_STOP_PCT = 0.10
LEG_TRAIL_START_PCT = 0.25
STRATEGY_TRAIL_START_PCT = 0.15
TRAIL_STEP_PCT = 0.10
FORCE_FLAT_END = True
MAX_NEW_TRADES_PER_DAY = 5
MAX_CONTRACTS_PER_TRADE = 5
SAVE_RESEARCH_SNAPSHOTS = False
OBJECT_STORE_PREFIX = 'vol_thesis_v3'
